#!/bin/bash

	clear
	stty erase '^?'
	
	echo -n "Database Host: "
	read HOST	
	echo -n "Database Name: "
	read DBNAME
	echo -n "Database User: "
	read DBUSER
	echo -n "Database Password: "
	read DBPASS
	echo -n "Store URL: "
	read URl
	
	echo -n "Version Magento : "
	read VERSION

    echo
    echo "Downloading packages..."
    echo

	wget http://www.magentocommerce.com/downloads/assets/$VERSION/magento-1.9.0.1.tar.gz
	wget http://www.silicon-village.fr/downloads/magento/assets/$VERSION/magento-sample-data-1.9.0.0.tar.gz

    echo
    echo "Extracting data..."
    echo

	tar -zxvf magento-$VERSION.tar.gz
	mv magento/* magento/.htaccess .
	mv magento-sample-data-$VERSION/magento_sample_data_for_$VERSION.sql magento/data.sql
	
	chmod -R o+w media var
	chmod o+w app/etc

    echo
    echo "Install magento ..."
    echo
	
	mysql -h $HOST -u $DBUSER -p$DBPASS $DBNAME < data.sql

    
    php install.php -- \
    --license_agreement_accepted "yes" \
    --locale "fr_FR" \
    --timezone "Indian/Mauritius" \
    --default_currency "EUR" \
    --db_host "localhost" \
    --db_name "skbox_001" \
    --db_user "user_skbox_001" \
    --db_pass "9g2A4ZFJ6Ict" \
    --admin_frontname "soukeo" \
    --use_rewrites "yes" \
    --use_secure "no" \
    --use_secure_admin "no" \
    --admin_firstname "Store" \
    --admin_lastname "Owner" \
    --admin_email "mamode@silicon-village.fr" \
    --url "http://94.23.233.226/hightech.re/" \
    --secure_base_url "https://94.23.233.226/hightech.re" \
    --admin_username "admin" \
    --admin_password "admin123"
    
    echo
    echo "Finished installing the latest stable version of Magento"
    echo

	echo
    echo "Application du themes de base"
    echo



rm -rf magento/ magento-1.9.0.0.tar.gz
